### ISSUE TITLE
EEException: Pixel grid dimensions (432000x144000) must be less than or equal to 10000.

### ISSUE THREAD

**Issue by manmeet3591** [KMarkert/cartoee#4]
I am trying to run the first example 

# plot the result using cartoee
ax = cee.getMap(srtm,region=bbox,visParams=visualization)

ax.coastlines()
plt.show()

and getting the following error. 

It seems this is due to some limit that GEE is capping. Can you please help me with this ?
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/data.py in _execute_cloud_call(call, num_retries)
    344   try:
--> 345     return call.execute(num_retries=num_retries)
    346   except googleapiclient.errors.HttpError as e:

~/anaconda3/envs/py36/lib/python3.6/site-packages/oauth2client/_helpers.py in positional_wrapper(*args, **kwargs)
    132                     logger.warning(message)
--> 133             return wrapped(*args, **kwargs)
    134         return positional_wrapper

~/anaconda3/envs/py36/lib/python3.6/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    841     if resp.status >= 300:
--> 842       raise HttpError(resp, content, uri=self.uri)
    843     return self.postproc(resp, content)

HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/thumbnails?fields=name&alt=json returned "Pixel grid dimensions (432000x144000) must be less than or equal to 10000.">

During handling of the above exception, another exception occurred:

EEException                               Traceback (most recent call last)
<ipython-input-9-365ce940e272> in <module>
      2 
      3 # plot the map
----> 4 ax = cee.getMap(srtm,cmap='terrain',region=bbox,visParams=visualization)
      5 # add a color bar using cartoee
      6 cb = cee.addColorbar(ax,loc='right',cmap='terrain',visParams=visualization)

~/anaconda3/envs/py36/lib/python3.6/site-packages/cartoee-0.0.5-py3.6.egg/cartoee/plotting.py in getMap(imgObj, proj, **kwargs)
     32 
     33     ax = plt.axes(projection=proj)
---> 34     ax = addLayer(imgObj,ax=ax,**kwargs)
     35 
     36     return ax

~/anaconda3/envs/py36/lib/python3.6/site-packages/cartoee-0.0.5-py3.6.egg/cartoee/plotting.py in addLayer(imgObj, ax, dims, region, cmap, visParams)
     94             args[key] = visParams[key]
     95 
---> 96     url = imgObj.getThumbUrl(args)
     97     img = urlopen(url)
     98     a = plt.imread(img)

~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/deprecation.py in Wrapper(*args, **kwargs)
     30           filename=func.__code__.co_filename,
     31           lineno=func.__code__.co_firstlineno + 1)
---> 32       return func(*args, **kwargs)
     33     deprecation_message = '\nDEPRECATED: ' + message
     34     try:

~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/image.py in getThumbURL(self, params)
    490     # behaviour.
    491     if data._use_cloud_api:  # pylint: disable=protected-access
--> 492       return data.makeThumbUrl(self.getThumbId(params))
    493     image, params = self._apply_visualization(params)
    494     params['image'] = image

~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/image.py in getThumbId(self, params)
    462     image, params = image._apply_visualization(params)  # pylint: disable=protected-access
    463     params['image'] = image
--> 464     return data.getThumbId(params)
    465 
    466   def getThumbURL(self, params=None):

~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/data.py in getThumbId(params, thumbType)
    822       result = _execute_cloud_call(
    823           _get_cloud_api_resource().projects().thumbnails().create(
--> 824               parent=_get_projects_path(), fields='name', body=request))
    825     return {'thumbid': result['name'], 'token': ''}
    826   request = params.copy()

~/anaconda3/envs/py36/lib/python3.6/site-packages/ee/data.py in _execute_cloud_call(call, num_retries)
    345     return call.execute(num_retries=num_retries)
    346   except googleapiclient.errors.HttpError as e:
--> 347     raise _translate_cloud_exception(e)
    348 
    349 

EEException: Pixel grid dimensions (432000x144000) must be less than or equal to 10000.

**Comment by KMarkert** [comment]
Hi @manmeet3591 👋 

Earth Engine changed their API a bit since I wrote this package so you will have to explicitly define another keyword to control the number of pixels EE returns to you. Here is the code:

```python
ax = cee.getMap(srtm,region=bbox,visParams=visualization,dims=4000)
ax.coastlines()
plt.show()
```

Note the `dims` keyword here. This controls the number of pixels for either the x or y dimension (EE will figure out the the actual dimensions to give you). Usually a value anywhere between 1000-5000 is good as the figure will not be able to display too much information past that. 

Here is the full documentation: https://cartoee.readthedocs.io/en/latest/api.html#cartoee.plotting.addLayer

**Comment by manmeet3591** [comment]
Thanks. This worked.

**Comment by khouakhi** [comment]
This example from the documentation of cartoee gives an error when adding cmap for the colorbar (but works when using custom palette) 

```
# get an earth engine image
srtm = ee.Image("CGIAR/SRTM90_V4")
# vis 
visualization = {'min':-500,'max':3000,'bands':'elevation'}
bbox = [-180,-90,180,90]

# plot the map
ax = cee.getMap(srtm,cmap='terrain',
                region=bbox,
                visParams=visualization,
                dims=1000)
# add a color bar using cartoee
cb = cee.addColorbar(ax,loc='right',
                     cmap='terrain',
                     visParams=visualization)

ax.coastlines()
```
TypeError                                 Traceback (most recent call last)
<ipython-input-55-14e80139c43d> in <module>()
     14 cb = cee.addColorbar(ax,loc='right',
     15                      cmap='terrain',
---> 16                      visParams=visualization)
     17 
     18 ax.coastlines()

2 frames
/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/__init__.py in _check_isinstance(_types, **kwargs)
   2126                     ", ".join(names[:-1]) + " or " + names[-1]
   2127                     if len(names) > 1 else names[0],
-> 2128                     type_name(type(v))))
   2129 
   2130 

TypeError: 'cmap' must be an instance of matplotlib.colors.Colormap or None, not a str

**Comment by joylilili98** [comment]
Hello @KMarkert, I  added "dims=4000"  to this code but new problems occurs

`UnsupportedOperation: seek`

and the latest details show that 
```
~\anaconda3\envs\gee\lib\site-packages\PIL\PngImagePlugin.py in read(self)
    159             s = self.fp.read(8)
    160             cid = s[4:]
--> 161             pos = self.fp.tell()
    162             length = i32(s)
    163 
```
This conda environment also has the package "geemap",  I was also wondering if cartoee module in geemap include all the functions of this cartoee package, or just the simple ones? Thanks very much!
